version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: alltools-backend
    ports:
      - "${PORT_BACKEND:-4001}:${INTERNAL_BACKEND:-4001}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: alltools-frontend
    ports:
      - "${PORT_FRONTEND:-3001}:${INTERNAL_FRONTEND:-3000}"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
